basePath: /api/v1
host: localhost:5000
info:
  contact:
    email: ramsureka007@gmail.com
    name: Utsav Sureka
    url: utsav.sureka@stl.tech
  description: API for Online Marketplace having several functionality to handle user,product
    and order details.
  title: Documenting API (Online Marketplace Apis)
  version: "2.0"
paths: {}
swagger: "2.0"
